[package]
name = "ftdc"
version = "0.1.0"
authors = ["Mark Benvenuto <mark.benvenuto@mongodb.com>"]

[dependencies]
bson = "0.13.0"
byteorder = "1.2.7"
libflate = "0.1.18"
structopt = "0.2.13"
indicatif = "0.9.0"
varinteger = "1.0.6"
chrono = "0.4.6"
streaming-iterator = "0.1.4"